import dotenv from 'dotenv';
dotenv.config();

const OPEN_WEATHER_API_KEY = process.env.OPEN_WEATHER_API_KEY;
const OPEN_WEATHER_CURRENT_WEATHER_API_URL = process.env.OPEN_WEATHER_CURRENT_WEATHER_API_URL;
const OPEN_WEATHER_WEATHER_5_DAYS_API_URL = process.env.OPEN_WEATHER_WEATHER_5_DAYS_API_URL;
const OPEN_WEATHER_DIRECT_GEOCODING_API_URL = process.env.OPEN_WEATHER_DIRECT_GEOCODING_API_URL;
const OPEN_WEATHER_ZIP_POST_GEOCODING_API_URL = process.env.OPEN_WEATHER_ZIP_POST_GEOCODING_API_URL;

export {
    OPEN_WEATHER_API_KEY,
    OPEN_WEATHER_CURRENT_WEATHER_API_URL,
    OPEN_WEATHER_WEATHER_5_DAYS_API_URL,
    OPEN_WEATHER_DIRECT_GEOCODING_API_URL,
    OPEN_WEATHER_ZIP_POST_GEOCODING_API_URL
}
