openapi: 3.0.3
info:
  title: Swagger NTGVN WebSocket
  description: NTGVN WebSocket
  version: 1.0.0.0
  contact:
    email: hoainhaannguyen@gmail.com
  license:
    name: MIT
servers:
  - url: http://0.0.0.0/v1/api
  - url: https://0.0.0.0/v1/api
paths:
  /ping:
    $ref: "./paths/ping.yaml"
components:
  schemas:
    Ping:
      $ref: "./schemas/ping.yaml"
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
